version: "2.1"

volumes:
  pihole_config: {}
  dnsmasq_config: {}

services:
  pihole:
    build: pihole
    cap_add:
      - SYS_TTY_CONFIG
      - NET_ADMIN
    volumes:
      - "pihole_config:/etc/pihole"
      - "dnsmasq_config:/etc/dnsmasq.d"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    network_mode: host
    labels:
      io.balena.features.dbus: "1"
    devices:
      - /dev/tty0
      - /dev/tty1
    tmpfs:
      - /var/log/pihole
    environment:
      DNSMASQ_LISTENING: all
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      FONTFACE: Terminus
      FONTSIZE: 8x14
      WEBPASSWORD: balena
      VIRTUAL_HOST: balena-devices.com
      WEB_BIND_ADDR: 0.0.0.0

  unbound:
    build: unbound
    ports:
      - "5053:5053/tcp"
      - "5053:5053/udp"

  # https://github.com/balenablocks/hostname
  # https://hub.balena.io/blocks/1918776/hostname-rpi
  hostname:
    image: bh.cr/g_tomas_migone1/hostname-rpi/0.2.1
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: pihole
